[package]
name = "k-armed_bandits_problem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
rand_distr = "0.3.0"
plotters = "0.3.1"